name: Run Playwright Tests and Publish Allure Report

on:
  push:
    branches: [master, main]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      FORGOT_PASSWORD_EMAIL: ${{ secrets.FORGOT_PASSWORD_EMAIL }}
      USER: ${{ secrets.USER  }}
      WRONG_PASSWORD: ${{ secrets.WRONG_PASSWORD }}
      BASE_URL: ${{secrets.BASE_URL}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run Playwright tests with Allure reporter
        run: npx playwright test --reporter=line,allure-playwright

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

  generate-report:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Allure results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Setup Java (required by Allure CLI)
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install Allure CLI
        run: npm install -g allure-commandline --save-dev

      - name: Generate Allure report
        run: allure generate allure-results --clean -o allure-report

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
